### ISSUE TITLE
How to prevent the filter from segmenting when a LF is encountered?

### ISSUE THREAD

**Issue by marcocevoli** [chelobaka/simple-latex-filter#1]
Hi,

First of all, thank you very much for this plugin.
I wanted to ask you: how can you prevent segmentation of sentences when a Line Feed (LF) is used in the source TEX files? These line feeds are ignored when generating the PDF file from TEX files. However, OmegaT detects them and segments the translation unit whenever it finds a line feed. I'd like OmegaT not to segment them.
Thanks in advance for your help.

**Comment by chelobaka** [comment]
@marcocevoli,

Segmentation is handled by OmegaT itself. The plugin doesn't touch single LF symbols. When I add LF symbols to text I see something like this in OmegaT (empty lines are segment boundaries) :

```
This is a first sentence.

Here goes LF symbol
inside a sentence.

LF symbol at the end of a sentence is not shown in OmegaT.

Here is another sentence.
``` 

If you do have new segments on LF symbols you might try to change your segmentation rules in OmegaT.

**Comment by marcocevoli** [comment]
Ok, changing the segmentation rules did the trick, but there's still an issue. All commands belonging to the third group, the ones that aren't rendered as tags, aren't shown in OmegaT (and that's fine), but a line break is added. See image: https://i.imgur.com/qnDLACK.png
In the source TEX file the command after "Procedure" is a \ref (followed by the section name). 
The expected behaviour would be that the closing parenthesis goes together with "Procedure".
And no, I don't have any segmentation rules that affect this text.

TIA

**Comment by chelobaka** [comment]
@marcocevoli 

During plugin development I missed the fact of existence of commands with no translatable content which should be inlined as tags. Besides that the default configuration has `\ref` command in CONTROL section which is wrong. As a quick fix you can move `\ref` to FORMAT section with one argument. Mark this argument as external if you don't won't to see reference strings inside your normal segments. This way you will get those reference strings as separate segments.

Currently I'm working on a proper solution where one would be able to describe FORMAT commands with non-translatable arguments.

**Comment by marcocevoli** [comment]
Thanks again, @chelobaka. 
Actually, I do want the reference strings inside the segment because - otherwise - the translation unit might be wrongly split. 
However, even though I set `\ref` as external: false, the plugin keeps putting a line break after it... Do you know where this line break comes from and how I can prevent it?

See https://i.imgur.com/7vhb5TL.png

I don't want the line break after the `<rf1/>` tag.

The good news is that I managed to get OmegaT to read the custom configuration file. :)

**Comment by chelobaka** [comment]
Can you provide a snippet from your tex file? You can change the actual text but keep commands intact.

**Comment by marcocevoli** [comment]
Sure, here it is:

```

\section{Lorem ipsum dolor sit amet, \label{sec:Lorem-setup}}

\subsection*{Do eiusmod tempor incididunt}

Lorem ipsum dolor sit amet, consectetur (Do eiusmod tempor incididunt \ref{sec:Lorem-ipsum-Abc2}).

\subsection*{Consectetur adipiscing elit}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
(Lorem ipsum dolor \ref{sec:ABC2-Eiusmod-Tempor}), and the lorem ipsum dolor 
dolorLorem ipsum dolor (Lorem 2020 Procedure \ref{sec:Microlorem-prep}).

\subsection*{Procedure}
\begin{enumerate}
\item magni dolores eos qui ratione voluptatem sequi nesciunt. 
magni dolores eos qui ratione voluptatem sequi nesciunt
liquid ex ea commodi consequatur? Quis
```

All line breaks above are LF (Unix-style line breaks, not CR-LF).
HIH.

**Comment by chelobaka** [comment]
@marcocevoli 

After some hacky tweaks your example now looks like this in OmegaT:

![Screenshot_20230912_214413](https://github.com/chelobaka/simple-latex-filter/assets/322618/f279d36c-6ba9-4d98-8161-2da3153f6b12)

Below you can find the new plugin version. You must run Java 11 or later to use it. Pick "fat" one if your OmegaT version is below 5.8. Before updating the plugin make sure to backup and remove your custom configuration file.

[SimpleLatexFilter-0.4.zip](https://github.com/chelobaka/simple-latex-filter/files/12589855/SimpleLatexFilter-0.4.zip)

Take a note: I didn't test it thoroughly, but it passes internal tests and works for your example.

Please report back on your experience.

**Comment by marcocevoli** [comment]
Brilliant! I have the same output. Thanks a lot. 
Our project has many files. If I spot other issues, I'll report them back here. Again, thanks.
