### ISSUE TITLE
Custom configuration ignored by the filter

### ISSUE THREAD

**Issue by marcocevoli** [chelobaka/simple-latex-filter#2]
Hi,

If I mark the option to load a custom configuration file and then edit the file (that is correctly created in OmegaT configuration folder), all edits to the JSON configuration file are ignored, even though I close and restart OmegaT.

Which folder is being monitored by the filter? 

I'm 100% positive that my modifications are syntactically correct because I tried to edit the config.json inside the JAR file and load that edited JAR files, and - in doing so - my modifications are taken into account.

I really appreciate any help you can provide.

Marco

**Comment by chelobaka** [comment]
@marcocevoli did you enable user configuration in filter settings?

**Comment by marcocevoli** [comment]
Yes, I did. And the custom configuration JSON file is created correctly in the OmegaT user configuration folder. However, if I edit that file, the changes are not taken into account, as if the filter isn't reading the JSON file.

**Comment by chelobaka** [comment]
Search for `[SimpleLatexFilter]` in OmegaT log. It should say where the plugin looks for configuration file.  The path is not hardcoded but requested by the plugin from OmegaT. I run Linux and user configuration works for me, though it wasn't tested with other OSes.

**Comment by marcocevoli** [comment]
Thanks again. Indeed, with that code I get the same result as with Access Configuration Folder command. What puzzles me is this: if you check the checkbox, the custom configuration file is correctly created in that folder.

However, until now, the plugin didn't consider any changes to that file. 

Now it works, so - apparently - I did something wrong before... If the issue occurs again, I'll let you know.
